#!/bin/bash
# Ubuntu
sudo apt update
sudo apt dist-upgrade -y
sudo apt autoremove -y

# GIT
sudo apt-add-repository ppa:git-core/ppa -y
sudo apt update
sudo apt install git -y

# Docker
sudo apt install ca-certificates curl gnupg lsb-release -y
wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
echo "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
sudo usermod -aG docker "$USER"

# Clone repository
git clone https://github.com/kokkekpek/traefik.git

# Copy files
cp .env traefik/.env
cp .htpasswd traefik/.htpasswd

# Create network
docker network create web

# Up container
cd traefik || exit
docker compose --env-file .env up -d