#!/bin/bash
# Ubuntu
sudo apt update
sudo apt dist-upgrade -y
sudo apt autoremove -y

# GIT
sudo apt-add-repository ppa:git-core/ppa -y
sudo apt update
sudo apt install git -y

# apache2-utils for htpasswd command
sudo apt install apache2-utils -y

# Docker
sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
wget -qO - https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88 -y
echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io -y
sudo usermod -aG docker "$USER"

# Docker compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# Clone repository
git clone https://github.com/kokkekpek/traefik.git

# Copy files
cp .env.example traefik/.env
cp .htpasswd.example traefik/.htpasswd

# Create network
docker network create web

# Up container
cd traefik || exit
docker-compose --env-file .env up -d