global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "traefik"
    static_configs:
      - targets: [ "traefik:8082" ]
  - job_name: "node"
    static_configs:
      - targets: ["nodeExporter:9100"]